name: Fetch Akeyless Secret

on:
  push:
    branches:
      - main

jobs:
  fetch_secrets:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Fetch static secret from Akeyless
        uses: akeyless-community/akeyless-github-action@v1.1.2
        id: fetch-secrets
        with:
          access-id: ${{ vars.AKEYLESS_ACCESS_ID }}
          access-type: jwt
          api-url: http://unified.id-aws.cs.akeyless.fans/api/v2
          static-secrets: |
            - name: "/Test/test_json_error"
              output-name: "my_secret"
      - name: Use Akeyless secret
        run: |
          echo "Step Outputs"
          echo "my_secret: ${{ steps.fetch-secrets.outputs.my_secret }}" >> secrets.txt
          echo "Environment Variables"
          echo "my_secret: ${{ env.my_secret }}" >> secrets.txt
